<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPCoREc3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPCoREc3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPCoREc3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPCoREc3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPCoREc3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PCoREc3',
    'container.build_id' => '7313f54a',
    'container.build_time' => 1651874412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPCoREc3');
