<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOQGAy6F\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOQGAy6F/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOQGAy6F.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOQGAy6F\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOQGAy6F\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OQGAy6F',
    'container.build_id' => 'a269d033',
    'container.build_time' => 1649829561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOQGAy6F');
